version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      - /etc/timezone:/etc/timezone:ro
    secrets:
      - mysql_root_password
      - mysql_user_password

  minio:
    build: ./minio
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ./database/minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_password
    secrets:
      - minio_password
      - synergy_user_password

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  express:
    build: ./express
    ports:
      - "${EXPRESS_PORT}:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD_FILE: /run/secrets/mysql_user_password
      DB_DATABASE: ${MYSQL_DATABASE}
      MINIO_HOST: ${SERVER_IP}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_password
      
    secrets:
      - mysql_user_password
      - minio_password

  checkin:
    build: 
      context: ./checkin
      dockerfile: Dockerfile
      args:
        - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}
    ports:
      - "${CHECKIN_PORT}:3000"
    environment:
      - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}

  po-from-excel:
    build:
      context: ./po-from-excel
      dockerfile: Dockerfile
      args:
        - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}
    ports:
      - "${PO_FROM_EXCEL_PORT}:3000"
    environment:
      - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}

  checkout:
    build:
      context: ./checkout
      dockerfile: Dockerfile
      args:
        - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}
    ports:
      - "${CHECKOUT_PORT}:3000"
    environment:
      - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}

  item-listing:
    build: 
      context: ./item-listing
      dockerfile: Dockerfile
      args:
        - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}
        - REACT_APP_UPLOAD_PICTURES_SERVER_ADDRESS=${SERVER_IP}:${UPLOAD_PICTURES_PORT}
    ports:
      - "${ITEM_LISTING_PORT}:3000"
    environment:
      - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}
      - REACT_APP_UPLOAD_PICTURES_SERVER_ADDRESS=${SERVER_IP}:${UPLOAD_PICTURES_PORT}

  upload-pictures:
    build: 
      context: ./upload-pictures
      dockerfile: Dockerfile
      args:
        - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}
    ports:
      - "${UPLOAD_PICTURES_PORT}:3000"
    environment:
      - REACT_APP_EXPRESS_SERVER_ADDRESS=${SERVER_IP}:${EXPRESS_PORT}

volumes:
  minio_data:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./database/mysql

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password
  minio_password:
    file: ./secrets/minio_password
  synergy_user_password:
    file: ./secrets/synergy_user_password
